‎name: Windows - RustDesk 32GB auto-restart
‎
‎on:
‎  workflow_dispatch:
‎
‎jobs:
‎  rustdesk-windows:
‎    name: Windows RustDesk RDP (Max RAM/CPU)
‎    runs-on: windows-latest
‎
‎    steps:
‎      - name: Download & Install RustDesk
‎        shell: powershell
‎        run: |
‎          Invoke-WebRequest `
‎            -Uri "https://gitlab.com/chamod12/win10-github-rdp-rustdesk/-/raw/main/Downloads.bat" `
‎            -OutFile "Downloads.bat"
‎          cmd /c Downloads.bat
‎
‎      - name: Show RustDesk ID
‎        shell: cmd
‎        run: |
‎          show.bat
‎
‎      - name: Keep Session Alive
‎        shell: cmd
‎        run: |
‎          python time.py
‎

